# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('geom', models.TextField()),
                ('srid', models.IntegerField(default=4326)),
                ('level', models.IntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='loss_db.AdministrativeDivision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(default=b'', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssetAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=255)),
                ('begin_date', models.DateField()),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskanalysis_analysistype', to='loss_db.AnalysisType')),
            ],
        ),
        migrations.CreateModel(
            name='DamageAssessmentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.DamageAssessment')),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('abstract', models.TextField()),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DamageTypeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[(b'dim1', b'dim1'), (b'dim2', b'dim2'), (b'dim3', b'dim3')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.AnalysisType')),
                ('damage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.DamageType')),
            ],
        ),
        migrations.CreateModel(
            name='EavAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=25)),
                ('begin_date', models.DateField()),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EntityType')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttributeValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EavAttribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mnemonic', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('order', models.IntegerField()),
                ('description', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='MarketValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.AssetItem')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phenomenon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField()),
                ('administrative_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.AdministrativeDivision')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SendaiIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(default=b'', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendaiTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(default=b'', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sendaiindicator',
            name='sendai_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.SendaiTarget'),
        ),
        migrations.AddField(
            model_name='event',
            name='hazard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Hazard'),
        ),
        migrations.AddField(
            model_name='eavattribute',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EntityType'),
        ),
        migrations.AddField(
            model_name='damagetypevalue',
            name='sendai_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.SendaiIndicator'),
        ),
        migrations.AddField(
            model_name='damageassessmentvalue',
            name='damage_type_value_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_dim1', to='loss_db.DamageTypeValue'),
        ),
        migrations.AddField(
            model_name='damageassessmentvalue',
            name='damage_type_value_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_dim2', to='loss_db.DamageTypeValue'),
        ),
        migrations.AddField(
            model_name='damageassessmentvalue',
            name='damage_type_value_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_dim3', to='loss_db.DamageTypeValue'),
        ),
        migrations.AddField(
            model_name='damageassessmentvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessed_damage', to='loss_db.AssetItem'),
        ),
        migrations.AddField(
            model_name='damageassessmentvalue',
            name='linked_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_assessed_damage', to='loss_db.AssetItem'),
        ),
        migrations.AddField(
            model_name='damageassessmentvalue',
            name='phenomenon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Phenomenon'),
        ),
        migrations.AddField(
            model_name='assetattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EavAttribute'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.AssetCategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EntityType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.AssetLocation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Owner'),
        ),
    ]
