# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name_plural': 'Asset categories'},
        ),
        migrations.AddField(
            model_name='event',
            name='attributes',
            field=models.ManyToManyField(through='loss_db.EventAttributeValue', to='loss_db.EavAttribute'),
        ),
        migrations.AlterField(
            model_name='damagetypevalue',
            name='damage_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.DamageAssessment'),
        ),
        migrations.AlterField(
            model_name='damagetypevalue',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
