# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0003_auto_20181105_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phenomenon',
            options={'verbose_name_plural': 'Phenomena'},
        ),
        migrations.AddField(
            model_name='eavattribute',
            name='code',
            field=models.CharField(default='notes', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eavattribute',
            name='data_type',
            field=models.CharField(choices=[(b'int', b'int'), (b'decimal', b'decimal'), (b'varchar', b'varchar'), (b'text', b'text')], default='varchar', max_length=30),
            preserve_default=False,
        ),
    ]
