# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0007_asset_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventAttributeValue',
            new_name='EventAttributeValueVarchar',
        ),
        migrations.AlterField(
            model_name='eavattribute',
            name='data_type',
            field=models.CharField(choices=[(b'int', b'int'), (b'decimal', b'decimal'), (b'varchar', b'varchar'), (b'text', b'text'), (b'date', b'date')], max_length=30),
        ),
    ]
