# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0009_eventattributevaluevarchar_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttributeValueDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[(b'date', b'date')], max_length=25)),
                ('value', models.DateField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EavAttribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventAttributeValueDecimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[(b'decimal', b'decimal')], max_length=25)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EavAttribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventAttributeValueInt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[(b'int', b'int')], max_length=25)),
                ('value', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EavAttribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventAttributeValueText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[(b'text', b'text')], max_length=25)),
                ('value', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.EavAttribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eventattributevaluevarchar',
            name='data_type',
            field=models.CharField(default=b'varchar', max_length=25),
        ),
    ]
