# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0011_auto_20181106_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlocation',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='administrative_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loss_db.AdministrativeDivision'),
        ),
    ]
