# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0012_auto_20181106_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageassessment',
            name='hazard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='riskanalysis_hazard', to='loss_db.Hazard'),
            preserve_default=False,
        ),
    ]
