# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0013_damageassessment_hazard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageassessmentvalue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
