# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0014_auto_20181107_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageassessmentvalue',
            name='damage_type_value_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_dim3', to='loss_db.DamageTypeValue'),
        ),
        migrations.AlterField(
            model_name='damageassessmentvalue',
            name='linked_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_assessed_damage', to='loss_db.AssetItem'),
        ),
    ]
