# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0015_auto_20181107_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketvalue',
            name='area_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marketvalue',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
