# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0016_auto_20181107_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[(b'fiexd_asset', b'fixed_asset'), (b'non_fixed_asset', b'non_fixed_asset'), (b'people', b'people')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
                ('administrative_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loss_db.AdministrativeDivision')),
            ],
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='administrative_division',
        ),
        migrations.RemoveField(
            model_name='damageassessmentvalue',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='damageassessmentvalue',
            name='lon',
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loss_db.Location'),
        ),
        migrations.DeleteModel(
            name='AssetLocation',
        ),
        migrations.AddField(
            model_name='damageassessmentvalue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_location', to='loss_db.Location'),
        ),
    ]
