# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0017_auto_20181107_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
