# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0018_auto_20181107_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistype',
            name='scope',
            field=models.CharField(choices=[(b'risk', b'risk'), (b'event', b'event')], default=(b'risk', b'risk'), max_length=25),
        ),
    ]
