# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0019_analysistype_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='code',
        ),
    ]
