# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loss_db', '0020_auto_20181113_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[(b'data_extraction', b'Data Extraction'), (b'cost_benefit_analysis', b'Cost Benefit Analysis'), (b'test', b'Test')], max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='damageassessment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_db_damageassessment', to=settings.AUTH_USER_MODEL, verbose_name=b'Owner'),
        ),
        migrations.AddField(
            model_name='damageassessment',
            name='state',
            field=models.CharField(choices=[(b'queued', b'Queued'), (b'processing', b'Processing'), (b'ready', b'Ready'), (b'error', b'Error'), (b'draft', b'Draft')], default=b'ready', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[(b'queued', b'Queued'), (b'processing', b'Processing'), (b'ready', b'Ready'), (b'error', b'Error'), (b'draft', b'Draft')], default=b'ready', max_length=64),
        ),
    ]
