# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 15:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loss_db', '0021_auto_20181113_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativedivision',
            name='srid',
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
